package com.scarb.model;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.COMMENT_ID
     *
     * @mbg.generated Tue Oct 18 10:52:33 CST 2016
     */
    private Integer commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.COMMENT_PARENTID
     *
     * @mbg.generated Tue Oct 18 10:52:33 CST 2016
     */
    private Integer commentParentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.COMMENT_AUTHORID
     *
     * @mbg.generated Tue Oct 18 10:52:33 CST 2016
     */
    private Integer commentAuthorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.COMMENT_CONTENT
     *
     * @mbg.generated Tue Oct 18 10:52:33 CST 2016
     */
    private String commentContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.COMMENT_TIME
     *
     * @mbg.generated Tue Oct 18 10:52:33 CST 2016
     */
    private String commentTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.COMMENT_ID
     *
     * @return the value of comment.COMMENT_ID
     *
     * @mbg.generated Tue Oct 18 10:52:33 CST 2016
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.COMMENT_ID
     *
     * @param commentId the value for comment.COMMENT_ID
     *
     * @mbg.generated Tue Oct 18 10:52:33 CST 2016
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.COMMENT_PARENTID
     *
     * @return the value of comment.COMMENT_PARENTID
     *
     * @mbg.generated Tue Oct 18 10:52:33 CST 2016
     */
    public Integer getCommentParentid() {
        return commentParentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.COMMENT_PARENTID
     *
     * @param commentParentid the value for comment.COMMENT_PARENTID
     *
     * @mbg.generated Tue Oct 18 10:52:33 CST 2016
     */
    public void setCommentParentid(Integer commentParentid) {
        this.commentParentid = commentParentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.COMMENT_AUTHORID
     *
     * @return the value of comment.COMMENT_AUTHORID
     *
     * @mbg.generated Tue Oct 18 10:52:33 CST 2016
     */
    public Integer getCommentAuthorid() {
        return commentAuthorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.COMMENT_AUTHORID
     *
     * @param commentAuthorid the value for comment.COMMENT_AUTHORID
     *
     * @mbg.generated Tue Oct 18 10:52:33 CST 2016
     */
    public void setCommentAuthorid(Integer commentAuthorid) {
        this.commentAuthorid = commentAuthorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.COMMENT_CONTENT
     *
     * @return the value of comment.COMMENT_CONTENT
     *
     * @mbg.generated Tue Oct 18 10:52:33 CST 2016
     */
    public String getCommentContent() {
        return commentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.COMMENT_CONTENT
     *
     * @param commentContent the value for comment.COMMENT_CONTENT
     *
     * @mbg.generated Tue Oct 18 10:52:33 CST 2016
     */
    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent == null ? null : commentContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.COMMENT_TIME
     *
     * @return the value of comment.COMMENT_TIME
     *
     * @mbg.generated Tue Oct 18 10:52:33 CST 2016
     */
    public String getCommentTime() {
        return commentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.COMMENT_TIME
     *
     * @param commentTime the value for comment.COMMENT_TIME
     *
     * @mbg.generated Tue Oct 18 10:52:33 CST 2016
     */
    public void setCommentTime(String commentTime) {
        this.commentTime = commentTime == null ? null : commentTime.trim();
    }
}