package com.scarb.model;

public class Ladder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ladder.ID
     *
     * @mbggenerated Thu Sep 08 15:30:41 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ladder.NAME
     *
     * @mbggenerated Thu Sep 08 15:30:41 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ladder.LEAGUE
     *
     * @mbggenerated Thu Sep 08 15:30:41 CST 2016
     */
    private String league;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ladder.QUEUE
     *
     * @mbggenerated Thu Sep 08 15:30:41 CST 2016
     */
    private String queue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ladder.PLAYERNUM
     *
     * @mbggenerated Thu Sep 08 15:30:41 CST 2016
     */
    private Integer playernum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ladder.ISCURRENT
     *
     * @mbggenerated Thu Sep 08 15:30:41 CST 2016
     */
    private Byte iscurrent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ladder.ID
     *
     * @return the value of ladder.ID
     *
     * @mbggenerated Thu Sep 08 15:30:41 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ladder.ID
     *
     * @param id the value for ladder.ID
     *
     * @mbggenerated Thu Sep 08 15:30:41 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ladder.NAME
     *
     * @return the value of ladder.NAME
     *
     * @mbggenerated Thu Sep 08 15:30:41 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ladder.NAME
     *
     * @param name the value for ladder.NAME
     *
     * @mbggenerated Thu Sep 08 15:30:41 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ladder.LEAGUE
     *
     * @return the value of ladder.LEAGUE
     *
     * @mbggenerated Thu Sep 08 15:30:41 CST 2016
     */
    public String getLeague() {
        return league;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ladder.LEAGUE
     *
     * @param league the value for ladder.LEAGUE
     *
     * @mbggenerated Thu Sep 08 15:30:41 CST 2016
     */
    public void setLeague(String league) {
        this.league = league == null ? null : league.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ladder.QUEUE
     *
     * @return the value of ladder.QUEUE
     *
     * @mbggenerated Thu Sep 08 15:30:41 CST 2016
     */
    public String getQueue() {
        return queue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ladder.QUEUE
     *
     * @param queue the value for ladder.QUEUE
     *
     * @mbggenerated Thu Sep 08 15:30:41 CST 2016
     */
    public void setQueue(String queue) {
        this.queue = queue == null ? null : queue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ladder.PLAYERNUM
     *
     * @return the value of ladder.PLAYERNUM
     *
     * @mbggenerated Thu Sep 08 15:30:41 CST 2016
     */
    public Integer getPlayernum() {
        return playernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ladder.PLAYERNUM
     *
     * @param playernum the value for ladder.PLAYERNUM
     *
     * @mbggenerated Thu Sep 08 15:30:41 CST 2016
     */
    public void setPlayernum(Integer playernum) {
        this.playernum = playernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ladder.ISCURRENT
     *
     * @return the value of ladder.ISCURRENT
     *
     * @mbggenerated Thu Sep 08 15:30:41 CST 2016
     */
    public Byte getIscurrent() {
        return iscurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ladder.ISCURRENT
     *
     * @param iscurrent the value for ladder.ISCURRENT
     *
     * @mbggenerated Thu Sep 08 15:30:41 CST 2016
     */
    public void setIscurrent(Byte iscurrent) {
        this.iscurrent = iscurrent;
    }
}