package com.scarb.model;

import java.util.ArrayList;
import java.util.List;

public class PlayerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table player
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table player
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table player
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public PlayerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table player
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSeasonIsNull() {
            addCriterion("season is null");
            return (Criteria) this;
        }

        public Criteria andSeasonIsNotNull() {
            addCriterion("season is not null");
            return (Criteria) this;
        }

        public Criteria andSeasonEqualTo(Integer value) {
            addCriterion("season =", value, "season");
            return (Criteria) this;
        }

        public Criteria andSeasonNotEqualTo(Integer value) {
            addCriterion("season <>", value, "season");
            return (Criteria) this;
        }

        public Criteria andSeasonGreaterThan(Integer value) {
            addCriterion("season >", value, "season");
            return (Criteria) this;
        }

        public Criteria andSeasonGreaterThanOrEqualTo(Integer value) {
            addCriterion("season >=", value, "season");
            return (Criteria) this;
        }

        public Criteria andSeasonLessThan(Integer value) {
            addCriterion("season <", value, "season");
            return (Criteria) this;
        }

        public Criteria andSeasonLessThanOrEqualTo(Integer value) {
            addCriterion("season <=", value, "season");
            return (Criteria) this;
        }

        public Criteria andSeasonIn(List<Integer> values) {
            addCriterion("season in", values, "season");
            return (Criteria) this;
        }

        public Criteria andSeasonNotIn(List<Integer> values) {
            addCriterion("season not in", values, "season");
            return (Criteria) this;
        }

        public Criteria andSeasonBetween(Integer value1, Integer value2) {
            addCriterion("season between", value1, value2, "season");
            return (Criteria) this;
        }

        public Criteria andSeasonNotBetween(Integer value1, Integer value2) {
            addCriterion("season not between", value1, value2, "season");
            return (Criteria) this;
        }

        public Criteria andRankIsNull() {
            addCriterion("rank is null");
            return (Criteria) this;
        }

        public Criteria andRankIsNotNull() {
            addCriterion("rank is not null");
            return (Criteria) this;
        }

        public Criteria andRankEqualTo(Integer value) {
            addCriterion("rank =", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankNotEqualTo(Integer value) {
            addCriterion("rank <>", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankGreaterThan(Integer value) {
            addCriterion("rank >", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankGreaterThanOrEqualTo(Integer value) {
            addCriterion("rank >=", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankLessThan(Integer value) {
            addCriterion("rank <", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankLessThanOrEqualTo(Integer value) {
            addCriterion("rank <=", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankIn(List<Integer> values) {
            addCriterion("rank in", values, "rank");
            return (Criteria) this;
        }

        public Criteria andRankNotIn(List<Integer> values) {
            addCriterion("rank not in", values, "rank");
            return (Criteria) this;
        }

        public Criteria andRankBetween(Integer value1, Integer value2) {
            addCriterion("rank between", value1, value2, "rank");
            return (Criteria) this;
        }

        public Criteria andRankNotBetween(Integer value1, Integer value2) {
            addCriterion("rank not between", value1, value2, "rank");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andBnetnameIsNull() {
            addCriterion("bnetname is null");
            return (Criteria) this;
        }

        public Criteria andBnetnameIsNotNull() {
            addCriterion("bnetname is not null");
            return (Criteria) this;
        }

        public Criteria andBnetnameEqualTo(String value) {
            addCriterion("bnetname =", value, "bnetname");
            return (Criteria) this;
        }

        public Criteria andBnetnameNotEqualTo(String value) {
            addCriterion("bnetname <>", value, "bnetname");
            return (Criteria) this;
        }

        public Criteria andBnetnameGreaterThan(String value) {
            addCriterion("bnetname >", value, "bnetname");
            return (Criteria) this;
        }

        public Criteria andBnetnameGreaterThanOrEqualTo(String value) {
            addCriterion("bnetname >=", value, "bnetname");
            return (Criteria) this;
        }

        public Criteria andBnetnameLessThan(String value) {
            addCriterion("bnetname <", value, "bnetname");
            return (Criteria) this;
        }

        public Criteria andBnetnameLessThanOrEqualTo(String value) {
            addCriterion("bnetname <=", value, "bnetname");
            return (Criteria) this;
        }

        public Criteria andBnetnameLike(String value) {
            addCriterion("bnetname like", value, "bnetname");
            return (Criteria) this;
        }

        public Criteria andBnetnameNotLike(String value) {
            addCriterion("bnetname not like", value, "bnetname");
            return (Criteria) this;
        }

        public Criteria andBnetnameIn(List<String> values) {
            addCriterion("bnetname in", values, "bnetname");
            return (Criteria) this;
        }

        public Criteria andBnetnameNotIn(List<String> values) {
            addCriterion("bnetname not in", values, "bnetname");
            return (Criteria) this;
        }

        public Criteria andBnetnameBetween(String value1, String value2) {
            addCriterion("bnetname between", value1, value2, "bnetname");
            return (Criteria) this;
        }

        public Criteria andBnetnameNotBetween(String value1, String value2) {
            addCriterion("bnetname not between", value1, value2, "bnetname");
            return (Criteria) this;
        }

        public Criteria andClannameIsNull() {
            addCriterion("clanName is null");
            return (Criteria) this;
        }

        public Criteria andClannameIsNotNull() {
            addCriterion("clanName is not null");
            return (Criteria) this;
        }

        public Criteria andClannameEqualTo(String value) {
            addCriterion("clanName =", value, "clanname");
            return (Criteria) this;
        }

        public Criteria andClannameNotEqualTo(String value) {
            addCriterion("clanName <>", value, "clanname");
            return (Criteria) this;
        }

        public Criteria andClannameGreaterThan(String value) {
            addCriterion("clanName >", value, "clanname");
            return (Criteria) this;
        }

        public Criteria andClannameGreaterThanOrEqualTo(String value) {
            addCriterion("clanName >=", value, "clanname");
            return (Criteria) this;
        }

        public Criteria andClannameLessThan(String value) {
            addCriterion("clanName <", value, "clanname");
            return (Criteria) this;
        }

        public Criteria andClannameLessThanOrEqualTo(String value) {
            addCriterion("clanName <=", value, "clanname");
            return (Criteria) this;
        }

        public Criteria andClannameLike(String value) {
            addCriterion("clanName like", value, "clanname");
            return (Criteria) this;
        }

        public Criteria andClannameNotLike(String value) {
            addCriterion("clanName not like", value, "clanname");
            return (Criteria) this;
        }

        public Criteria andClannameIn(List<String> values) {
            addCriterion("clanName in", values, "clanname");
            return (Criteria) this;
        }

        public Criteria andClannameNotIn(List<String> values) {
            addCriterion("clanName not in", values, "clanname");
            return (Criteria) this;
        }

        public Criteria andClannameBetween(String value1, String value2) {
            addCriterion("clanName between", value1, value2, "clanname");
            return (Criteria) this;
        }

        public Criteria andClannameNotBetween(String value1, String value2) {
            addCriterion("clanName not between", value1, value2, "clanname");
            return (Criteria) this;
        }

        public Criteria andClantagIsNull() {
            addCriterion("clanTag is null");
            return (Criteria) this;
        }

        public Criteria andClantagIsNotNull() {
            addCriterion("clanTag is not null");
            return (Criteria) this;
        }

        public Criteria andClantagEqualTo(String value) {
            addCriterion("clanTag =", value, "clantag");
            return (Criteria) this;
        }

        public Criteria andClantagNotEqualTo(String value) {
            addCriterion("clanTag <>", value, "clantag");
            return (Criteria) this;
        }

        public Criteria andClantagGreaterThan(String value) {
            addCriterion("clanTag >", value, "clantag");
            return (Criteria) this;
        }

        public Criteria andClantagGreaterThanOrEqualTo(String value) {
            addCriterion("clanTag >=", value, "clantag");
            return (Criteria) this;
        }

        public Criteria andClantagLessThan(String value) {
            addCriterion("clanTag <", value, "clantag");
            return (Criteria) this;
        }

        public Criteria andClantagLessThanOrEqualTo(String value) {
            addCriterion("clanTag <=", value, "clantag");
            return (Criteria) this;
        }

        public Criteria andClantagLike(String value) {
            addCriterion("clanTag like", value, "clantag");
            return (Criteria) this;
        }

        public Criteria andClantagNotLike(String value) {
            addCriterion("clanTag not like", value, "clantag");
            return (Criteria) this;
        }

        public Criteria andClantagIn(List<String> values) {
            addCriterion("clanTag in", values, "clantag");
            return (Criteria) this;
        }

        public Criteria andClantagNotIn(List<String> values) {
            addCriterion("clanTag not in", values, "clantag");
            return (Criteria) this;
        }

        public Criteria andClantagBetween(String value1, String value2) {
            addCriterion("clanTag between", value1, value2, "clantag");
            return (Criteria) this;
        }

        public Criteria andClantagNotBetween(String value1, String value2) {
            addCriterion("clanTag not between", value1, value2, "clantag");
            return (Criteria) this;
        }

        public Criteria andFavoriteraceIsNull() {
            addCriterion("favoriteRace is null");
            return (Criteria) this;
        }

        public Criteria andFavoriteraceIsNotNull() {
            addCriterion("favoriteRace is not null");
            return (Criteria) this;
        }

        public Criteria andFavoriteraceEqualTo(String value) {
            addCriterion("favoriteRace =", value, "favoriterace");
            return (Criteria) this;
        }

        public Criteria andFavoriteraceNotEqualTo(String value) {
            addCriterion("favoriteRace <>", value, "favoriterace");
            return (Criteria) this;
        }

        public Criteria andFavoriteraceGreaterThan(String value) {
            addCriterion("favoriteRace >", value, "favoriterace");
            return (Criteria) this;
        }

        public Criteria andFavoriteraceGreaterThanOrEqualTo(String value) {
            addCriterion("favoriteRace >=", value, "favoriterace");
            return (Criteria) this;
        }

        public Criteria andFavoriteraceLessThan(String value) {
            addCriterion("favoriteRace <", value, "favoriterace");
            return (Criteria) this;
        }

        public Criteria andFavoriteraceLessThanOrEqualTo(String value) {
            addCriterion("favoriteRace <=", value, "favoriterace");
            return (Criteria) this;
        }

        public Criteria andFavoriteraceLike(String value) {
            addCriterion("favoriteRace like", value, "favoriterace");
            return (Criteria) this;
        }

        public Criteria andFavoriteraceNotLike(String value) {
            addCriterion("favoriteRace not like", value, "favoriterace");
            return (Criteria) this;
        }

        public Criteria andFavoriteraceIn(List<String> values) {
            addCriterion("favoriteRace in", values, "favoriterace");
            return (Criteria) this;
        }

        public Criteria andFavoriteraceNotIn(List<String> values) {
            addCriterion("favoriteRace not in", values, "favoriterace");
            return (Criteria) this;
        }

        public Criteria andFavoriteraceBetween(String value1, String value2) {
            addCriterion("favoriteRace between", value1, value2, "favoriterace");
            return (Criteria) this;
        }

        public Criteria andFavoriteraceNotBetween(String value1, String value2) {
            addCriterion("favoriteRace not between", value1, value2, "favoriterace");
            return (Criteria) this;
        }

        public Criteria andLeagueIsNull() {
            addCriterion("league is null");
            return (Criteria) this;
        }

        public Criteria andLeagueIsNotNull() {
            addCriterion("league is not null");
            return (Criteria) this;
        }

        public Criteria andLeagueEqualTo(String value) {
            addCriterion("league =", value, "league");
            return (Criteria) this;
        }

        public Criteria andLeagueNotEqualTo(String value) {
            addCriterion("league <>", value, "league");
            return (Criteria) this;
        }

        public Criteria andLeagueGreaterThan(String value) {
            addCriterion("league >", value, "league");
            return (Criteria) this;
        }

        public Criteria andLeagueGreaterThanOrEqualTo(String value) {
            addCriterion("league >=", value, "league");
            return (Criteria) this;
        }

        public Criteria andLeagueLessThan(String value) {
            addCriterion("league <", value, "league");
            return (Criteria) this;
        }

        public Criteria andLeagueLessThanOrEqualTo(String value) {
            addCriterion("league <=", value, "league");
            return (Criteria) this;
        }

        public Criteria andLeagueLike(String value) {
            addCriterion("league like", value, "league");
            return (Criteria) this;
        }

        public Criteria andLeagueNotLike(String value) {
            addCriterion("league not like", value, "league");
            return (Criteria) this;
        }

        public Criteria andLeagueIn(List<String> values) {
            addCriterion("league in", values, "league");
            return (Criteria) this;
        }

        public Criteria andLeagueNotIn(List<String> values) {
            addCriterion("league not in", values, "league");
            return (Criteria) this;
        }

        public Criteria andLeagueBetween(String value1, String value2) {
            addCriterion("league between", value1, value2, "league");
            return (Criteria) this;
        }

        public Criteria andLeagueNotBetween(String value1, String value2) {
            addCriterion("league not between", value1, value2, "league");
            return (Criteria) this;
        }

        public Criteria andTierIsNull() {
            addCriterion("tier is null");
            return (Criteria) this;
        }

        public Criteria andTierIsNotNull() {
            addCriterion("tier is not null");
            return (Criteria) this;
        }

        public Criteria andTierEqualTo(Integer value) {
            addCriterion("tier =", value, "tier");
            return (Criteria) this;
        }

        public Criteria andTierNotEqualTo(Integer value) {
            addCriterion("tier <>", value, "tier");
            return (Criteria) this;
        }

        public Criteria andTierGreaterThan(Integer value) {
            addCriterion("tier >", value, "tier");
            return (Criteria) this;
        }

        public Criteria andTierGreaterThanOrEqualTo(Integer value) {
            addCriterion("tier >=", value, "tier");
            return (Criteria) this;
        }

        public Criteria andTierLessThan(Integer value) {
            addCriterion("tier <", value, "tier");
            return (Criteria) this;
        }

        public Criteria andTierLessThanOrEqualTo(Integer value) {
            addCriterion("tier <=", value, "tier");
            return (Criteria) this;
        }

        public Criteria andTierIn(List<Integer> values) {
            addCriterion("tier in", values, "tier");
            return (Criteria) this;
        }

        public Criteria andTierNotIn(List<Integer> values) {
            addCriterion("tier not in", values, "tier");
            return (Criteria) this;
        }

        public Criteria andTierBetween(Integer value1, Integer value2) {
            addCriterion("tier between", value1, value2, "tier");
            return (Criteria) this;
        }

        public Criteria andTierNotBetween(Integer value1, Integer value2) {
            addCriterion("tier not between", value1, value2, "tier");
            return (Criteria) this;
        }

        public Criteria andMmrIsNull() {
            addCriterion("mmr is null");
            return (Criteria) this;
        }

        public Criteria andMmrIsNotNull() {
            addCriterion("mmr is not null");
            return (Criteria) this;
        }

        public Criteria andMmrEqualTo(Integer value) {
            addCriterion("mmr =", value, "mmr");
            return (Criteria) this;
        }

        public Criteria andMmrNotEqualTo(Integer value) {
            addCriterion("mmr <>", value, "mmr");
            return (Criteria) this;
        }

        public Criteria andMmrGreaterThan(Integer value) {
            addCriterion("mmr >", value, "mmr");
            return (Criteria) this;
        }

        public Criteria andMmrGreaterThanOrEqualTo(Integer value) {
            addCriterion("mmr >=", value, "mmr");
            return (Criteria) this;
        }

        public Criteria andMmrLessThan(Integer value) {
            addCriterion("mmr <", value, "mmr");
            return (Criteria) this;
        }

        public Criteria andMmrLessThanOrEqualTo(Integer value) {
            addCriterion("mmr <=", value, "mmr");
            return (Criteria) this;
        }

        public Criteria andMmrIn(List<Integer> values) {
            addCriterion("mmr in", values, "mmr");
            return (Criteria) this;
        }

        public Criteria andMmrNotIn(List<Integer> values) {
            addCriterion("mmr not in", values, "mmr");
            return (Criteria) this;
        }

        public Criteria andMmrBetween(Integer value1, Integer value2) {
            addCriterion("mmr between", value1, value2, "mmr");
            return (Criteria) this;
        }

        public Criteria andMmrNotBetween(Integer value1, Integer value2) {
            addCriterion("mmr not between", value1, value2, "mmr");
            return (Criteria) this;
        }

        public Criteria andPointsIsNull() {
            addCriterion("points is null");
            return (Criteria) this;
        }

        public Criteria andPointsIsNotNull() {
            addCriterion("points is not null");
            return (Criteria) this;
        }

        public Criteria andPointsEqualTo(Integer value) {
            addCriterion("points =", value, "points");
            return (Criteria) this;
        }

        public Criteria andPointsNotEqualTo(Integer value) {
            addCriterion("points <>", value, "points");
            return (Criteria) this;
        }

        public Criteria andPointsGreaterThan(Integer value) {
            addCriterion("points >", value, "points");
            return (Criteria) this;
        }

        public Criteria andPointsGreaterThanOrEqualTo(Integer value) {
            addCriterion("points >=", value, "points");
            return (Criteria) this;
        }

        public Criteria andPointsLessThan(Integer value) {
            addCriterion("points <", value, "points");
            return (Criteria) this;
        }

        public Criteria andPointsLessThanOrEqualTo(Integer value) {
            addCriterion("points <=", value, "points");
            return (Criteria) this;
        }

        public Criteria andPointsIn(List<Integer> values) {
            addCriterion("points in", values, "points");
            return (Criteria) this;
        }

        public Criteria andPointsNotIn(List<Integer> values) {
            addCriterion("points not in", values, "points");
            return (Criteria) this;
        }

        public Criteria andPointsBetween(Integer value1, Integer value2) {
            addCriterion("points between", value1, value2, "points");
            return (Criteria) this;
        }

        public Criteria andPointsNotBetween(Integer value1, Integer value2) {
            addCriterion("points not between", value1, value2, "points");
            return (Criteria) this;
        }

        public Criteria andWinsIsNull() {
            addCriterion("wins is null");
            return (Criteria) this;
        }

        public Criteria andWinsIsNotNull() {
            addCriterion("wins is not null");
            return (Criteria) this;
        }

        public Criteria andWinsEqualTo(Integer value) {
            addCriterion("wins =", value, "wins");
            return (Criteria) this;
        }

        public Criteria andWinsNotEqualTo(Integer value) {
            addCriterion("wins <>", value, "wins");
            return (Criteria) this;
        }

        public Criteria andWinsGreaterThan(Integer value) {
            addCriterion("wins >", value, "wins");
            return (Criteria) this;
        }

        public Criteria andWinsGreaterThanOrEqualTo(Integer value) {
            addCriterion("wins >=", value, "wins");
            return (Criteria) this;
        }

        public Criteria andWinsLessThan(Integer value) {
            addCriterion("wins <", value, "wins");
            return (Criteria) this;
        }

        public Criteria andWinsLessThanOrEqualTo(Integer value) {
            addCriterion("wins <=", value, "wins");
            return (Criteria) this;
        }

        public Criteria andWinsIn(List<Integer> values) {
            addCriterion("wins in", values, "wins");
            return (Criteria) this;
        }

        public Criteria andWinsNotIn(List<Integer> values) {
            addCriterion("wins not in", values, "wins");
            return (Criteria) this;
        }

        public Criteria andWinsBetween(Integer value1, Integer value2) {
            addCriterion("wins between", value1, value2, "wins");
            return (Criteria) this;
        }

        public Criteria andWinsNotBetween(Integer value1, Integer value2) {
            addCriterion("wins not between", value1, value2, "wins");
            return (Criteria) this;
        }

        public Criteria andLossesIsNull() {
            addCriterion("losses is null");
            return (Criteria) this;
        }

        public Criteria andLossesIsNotNull() {
            addCriterion("losses is not null");
            return (Criteria) this;
        }

        public Criteria andLossesEqualTo(Integer value) {
            addCriterion("losses =", value, "losses");
            return (Criteria) this;
        }

        public Criteria andLossesNotEqualTo(Integer value) {
            addCriterion("losses <>", value, "losses");
            return (Criteria) this;
        }

        public Criteria andLossesGreaterThan(Integer value) {
            addCriterion("losses >", value, "losses");
            return (Criteria) this;
        }

        public Criteria andLossesGreaterThanOrEqualTo(Integer value) {
            addCriterion("losses >=", value, "losses");
            return (Criteria) this;
        }

        public Criteria andLossesLessThan(Integer value) {
            addCriterion("losses <", value, "losses");
            return (Criteria) this;
        }

        public Criteria andLossesLessThanOrEqualTo(Integer value) {
            addCriterion("losses <=", value, "losses");
            return (Criteria) this;
        }

        public Criteria andLossesIn(List<Integer> values) {
            addCriterion("losses in", values, "losses");
            return (Criteria) this;
        }

        public Criteria andLossesNotIn(List<Integer> values) {
            addCriterion("losses not in", values, "losses");
            return (Criteria) this;
        }

        public Criteria andLossesBetween(Integer value1, Integer value2) {
            addCriterion("losses between", value1, value2, "losses");
            return (Criteria) this;
        }

        public Criteria andLossesNotBetween(Integer value1, Integer value2) {
            addCriterion("losses not between", value1, value2, "losses");
            return (Criteria) this;
        }

        public Criteria andTiesIsNull() {
            addCriterion("ties is null");
            return (Criteria) this;
        }

        public Criteria andTiesIsNotNull() {
            addCriterion("ties is not null");
            return (Criteria) this;
        }

        public Criteria andTiesEqualTo(Integer value) {
            addCriterion("ties =", value, "ties");
            return (Criteria) this;
        }

        public Criteria andTiesNotEqualTo(Integer value) {
            addCriterion("ties <>", value, "ties");
            return (Criteria) this;
        }

        public Criteria andTiesGreaterThan(Integer value) {
            addCriterion("ties >", value, "ties");
            return (Criteria) this;
        }

        public Criteria andTiesGreaterThanOrEqualTo(Integer value) {
            addCriterion("ties >=", value, "ties");
            return (Criteria) this;
        }

        public Criteria andTiesLessThan(Integer value) {
            addCriterion("ties <", value, "ties");
            return (Criteria) this;
        }

        public Criteria andTiesLessThanOrEqualTo(Integer value) {
            addCriterion("ties <=", value, "ties");
            return (Criteria) this;
        }

        public Criteria andTiesIn(List<Integer> values) {
            addCriterion("ties in", values, "ties");
            return (Criteria) this;
        }

        public Criteria andTiesNotIn(List<Integer> values) {
            addCriterion("ties not in", values, "ties");
            return (Criteria) this;
        }

        public Criteria andTiesBetween(Integer value1, Integer value2) {
            addCriterion("ties between", value1, value2, "ties");
            return (Criteria) this;
        }

        public Criteria andTiesNotBetween(Integer value1, Integer value2) {
            addCriterion("ties not between", value1, value2, "ties");
            return (Criteria) this;
        }

        public Criteria andLadderidIsNull() {
            addCriterion("ladderid is null");
            return (Criteria) this;
        }

        public Criteria andLadderidIsNotNull() {
            addCriterion("ladderid is not null");
            return (Criteria) this;
        }

        public Criteria andLadderidEqualTo(Integer value) {
            addCriterion("ladderid =", value, "ladderid");
            return (Criteria) this;
        }

        public Criteria andLadderidNotEqualTo(Integer value) {
            addCriterion("ladderid <>", value, "ladderid");
            return (Criteria) this;
        }

        public Criteria andLadderidGreaterThan(Integer value) {
            addCriterion("ladderid >", value, "ladderid");
            return (Criteria) this;
        }

        public Criteria andLadderidGreaterThanOrEqualTo(Integer value) {
            addCriterion("ladderid >=", value, "ladderid");
            return (Criteria) this;
        }

        public Criteria andLadderidLessThan(Integer value) {
            addCriterion("ladderid <", value, "ladderid");
            return (Criteria) this;
        }

        public Criteria andLadderidLessThanOrEqualTo(Integer value) {
            addCriterion("ladderid <=", value, "ladderid");
            return (Criteria) this;
        }

        public Criteria andLadderidIn(List<Integer> values) {
            addCriterion("ladderid in", values, "ladderid");
            return (Criteria) this;
        }

        public Criteria andLadderidNotIn(List<Integer> values) {
            addCriterion("ladderid not in", values, "ladderid");
            return (Criteria) this;
        }

        public Criteria andLadderidBetween(Integer value1, Integer value2) {
            addCriterion("ladderid between", value1, value2, "ladderid");
            return (Criteria) this;
        }

        public Criteria andLadderidNotBetween(Integer value1, Integer value2) {
            addCriterion("ladderid not between", value1, value2, "ladderid");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("updateTime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("updateTime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Integer value) {
            addCriterion("updateTime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Integer value) {
            addCriterion("updateTime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Integer value) {
            addCriterion("updateTime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("updateTime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Integer value) {
            addCriterion("updateTime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Integer value) {
            addCriterion("updateTime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Integer> values) {
            addCriterion("updateTime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Integer> values) {
            addCriterion("updateTime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Integer value1, Integer value2) {
            addCriterion("updateTime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Integer value1, Integer value2) {
            addCriterion("updateTime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andLastplayedtimeIsNull() {
            addCriterion("lastPlayedTime is null");
            return (Criteria) this;
        }

        public Criteria andLastplayedtimeIsNotNull() {
            addCriterion("lastPlayedTime is not null");
            return (Criteria) this;
        }

        public Criteria andLastplayedtimeEqualTo(Integer value) {
            addCriterion("lastPlayedTime =", value, "lastplayedtime");
            return (Criteria) this;
        }

        public Criteria andLastplayedtimeNotEqualTo(Integer value) {
            addCriterion("lastPlayedTime <>", value, "lastplayedtime");
            return (Criteria) this;
        }

        public Criteria andLastplayedtimeGreaterThan(Integer value) {
            addCriterion("lastPlayedTime >", value, "lastplayedtime");
            return (Criteria) this;
        }

        public Criteria andLastplayedtimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("lastPlayedTime >=", value, "lastplayedtime");
            return (Criteria) this;
        }

        public Criteria andLastplayedtimeLessThan(Integer value) {
            addCriterion("lastPlayedTime <", value, "lastplayedtime");
            return (Criteria) this;
        }

        public Criteria andLastplayedtimeLessThanOrEqualTo(Integer value) {
            addCriterion("lastPlayedTime <=", value, "lastplayedtime");
            return (Criteria) this;
        }

        public Criteria andLastplayedtimeIn(List<Integer> values) {
            addCriterion("lastPlayedTime in", values, "lastplayedtime");
            return (Criteria) this;
        }

        public Criteria andLastplayedtimeNotIn(List<Integer> values) {
            addCriterion("lastPlayedTime not in", values, "lastplayedtime");
            return (Criteria) this;
        }

        public Criteria andLastplayedtimeBetween(Integer value1, Integer value2) {
            addCriterion("lastPlayedTime between", value1, value2, "lastplayedtime");
            return (Criteria) this;
        }

        public Criteria andLastplayedtimeNotBetween(Integer value1, Integer value2) {
            addCriterion("lastPlayedTime not between", value1, value2, "lastplayedtime");
            return (Criteria) this;
        }

        public Criteria andJointimeIsNull() {
            addCriterion("joinTime is null");
            return (Criteria) this;
        }

        public Criteria andJointimeIsNotNull() {
            addCriterion("joinTime is not null");
            return (Criteria) this;
        }

        public Criteria andJointimeEqualTo(Integer value) {
            addCriterion("joinTime =", value, "jointime");
            return (Criteria) this;
        }

        public Criteria andJointimeNotEqualTo(Integer value) {
            addCriterion("joinTime <>", value, "jointime");
            return (Criteria) this;
        }

        public Criteria andJointimeGreaterThan(Integer value) {
            addCriterion("joinTime >", value, "jointime");
            return (Criteria) this;
        }

        public Criteria andJointimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("joinTime >=", value, "jointime");
            return (Criteria) this;
        }

        public Criteria andJointimeLessThan(Integer value) {
            addCriterion("joinTime <", value, "jointime");
            return (Criteria) this;
        }

        public Criteria andJointimeLessThanOrEqualTo(Integer value) {
            addCriterion("joinTime <=", value, "jointime");
            return (Criteria) this;
        }

        public Criteria andJointimeIn(List<Integer> values) {
            addCriterion("joinTime in", values, "jointime");
            return (Criteria) this;
        }

        public Criteria andJointimeNotIn(List<Integer> values) {
            addCriterion("joinTime not in", values, "jointime");
            return (Criteria) this;
        }

        public Criteria andJointimeBetween(Integer value1, Integer value2) {
            addCriterion("joinTime between", value1, value2, "jointime");
            return (Criteria) this;
        }

        public Criteria andJointimeNotBetween(Integer value1, Integer value2) {
            addCriterion("joinTime not between", value1, value2, "jointime");
            return (Criteria) this;
        }

        public Criteria andWinrateIsNull() {
            addCriterion("winRate is null");
            return (Criteria) this;
        }

        public Criteria andWinrateIsNotNull() {
            addCriterion("winRate is not null");
            return (Criteria) this;
        }

        public Criteria andWinrateEqualTo(Integer value) {
            addCriterion("winRate =", value, "winrate");
            return (Criteria) this;
        }

        public Criteria andWinrateNotEqualTo(Integer value) {
            addCriterion("winRate <>", value, "winrate");
            return (Criteria) this;
        }

        public Criteria andWinrateGreaterThan(Integer value) {
            addCriterion("winRate >", value, "winrate");
            return (Criteria) this;
        }

        public Criteria andWinrateGreaterThanOrEqualTo(Integer value) {
            addCriterion("winRate >=", value, "winrate");
            return (Criteria) this;
        }

        public Criteria andWinrateLessThan(Integer value) {
            addCriterion("winRate <", value, "winrate");
            return (Criteria) this;
        }

        public Criteria andWinrateLessThanOrEqualTo(Integer value) {
            addCriterion("winRate <=", value, "winrate");
            return (Criteria) this;
        }

        public Criteria andWinrateIn(List<Integer> values) {
            addCriterion("winRate in", values, "winrate");
            return (Criteria) this;
        }

        public Criteria andWinrateNotIn(List<Integer> values) {
            addCriterion("winRate not in", values, "winrate");
            return (Criteria) this;
        }

        public Criteria andWinrateBetween(Integer value1, Integer value2) {
            addCriterion("winRate between", value1, value2, "winrate");
            return (Criteria) this;
        }

        public Criteria andWinrateNotBetween(Integer value1, Integer value2) {
            addCriterion("winRate not between", value1, value2, "winrate");
            return (Criteria) this;
        }

        public Criteria andProfilepathIsNull() {
            addCriterion("profilePath is null");
            return (Criteria) this;
        }

        public Criteria andProfilepathIsNotNull() {
            addCriterion("profilePath is not null");
            return (Criteria) this;
        }

        public Criteria andProfilepathEqualTo(String value) {
            addCriterion("profilePath =", value, "profilepath");
            return (Criteria) this;
        }

        public Criteria andProfilepathNotEqualTo(String value) {
            addCriterion("profilePath <>", value, "profilepath");
            return (Criteria) this;
        }

        public Criteria andProfilepathGreaterThan(String value) {
            addCriterion("profilePath >", value, "profilepath");
            return (Criteria) this;
        }

        public Criteria andProfilepathGreaterThanOrEqualTo(String value) {
            addCriterion("profilePath >=", value, "profilepath");
            return (Criteria) this;
        }

        public Criteria andProfilepathLessThan(String value) {
            addCriterion("profilePath <", value, "profilepath");
            return (Criteria) this;
        }

        public Criteria andProfilepathLessThanOrEqualTo(String value) {
            addCriterion("profilePath <=", value, "profilepath");
            return (Criteria) this;
        }

        public Criteria andProfilepathLike(String value) {
            addCriterion("profilePath like", value, "profilepath");
            return (Criteria) this;
        }

        public Criteria andProfilepathNotLike(String value) {
            addCriterion("profilePath not like", value, "profilepath");
            return (Criteria) this;
        }

        public Criteria andProfilepathIn(List<String> values) {
            addCriterion("profilePath in", values, "profilepath");
            return (Criteria) this;
        }

        public Criteria andProfilepathNotIn(List<String> values) {
            addCriterion("profilePath not in", values, "profilepath");
            return (Criteria) this;
        }

        public Criteria andProfilepathBetween(String value1, String value2) {
            addCriterion("profilePath between", value1, value2, "profilepath");
            return (Criteria) this;
        }

        public Criteria andProfilepathNotBetween(String value1, String value2) {
            addCriterion("profilePath not between", value1, value2, "profilepath");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table player
     *
     * @mbg.generated do_not_delete_during_merge Thu Dec 01 12:30:10 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table player
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}