package com.scarb.model;

public class Player {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.id
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.season
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    private Integer season;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.rank
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    private Integer rank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.name
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.bnetname
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    private String bnetname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.clanName
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    private String clanname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.clanTag
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    private String clantag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.favoriteRace
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    private String favoriterace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.league
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    private String league;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.tier
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    private Integer tier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.mmr
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    private Integer mmr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.points
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    private Integer points;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.wins
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    private Integer wins;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.losses
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    private Integer losses;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.ties
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    private Integer ties;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.ladderid
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    private Integer ladderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.updateTime
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    private Integer updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.lastPlayedTime
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    private Integer lastplayedtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.joinTime
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    private Integer jointime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.winRate
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    private Integer winrate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.profilePath
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    private String profilepath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.id
     *
     * @return the value of player.id
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.id
     *
     * @param id the value for player.id
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.season
     *
     * @return the value of player.season
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public Integer getSeason() {
        return season;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.season
     *
     * @param season the value for player.season
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public void setSeason(Integer season) {
        this.season = season;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.rank
     *
     * @return the value of player.rank
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public Integer getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.rank
     *
     * @param rank the value for player.rank
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public void setRank(Integer rank) {
        this.rank = rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.name
     *
     * @return the value of player.name
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.name
     *
     * @param name the value for player.name
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.bnetname
     *
     * @return the value of player.bnetname
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public String getBnetname() {
        return bnetname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.bnetname
     *
     * @param bnetname the value for player.bnetname
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public void setBnetname(String bnetname) {
        this.bnetname = bnetname == null ? null : bnetname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.clanName
     *
     * @return the value of player.clanName
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public String getClanname() {
        return clanname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.clanName
     *
     * @param clanname the value for player.clanName
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public void setClanname(String clanname) {
        this.clanname = clanname == null ? null : clanname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.clanTag
     *
     * @return the value of player.clanTag
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public String getClantag() {
        return clantag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.clanTag
     *
     * @param clantag the value for player.clanTag
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public void setClantag(String clantag) {
        this.clantag = clantag == null ? null : clantag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.favoriteRace
     *
     * @return the value of player.favoriteRace
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public String getFavoriterace() {
        return favoriterace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.favoriteRace
     *
     * @param favoriterace the value for player.favoriteRace
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public void setFavoriterace(String favoriterace) {
        this.favoriterace = favoriterace == null ? null : favoriterace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.league
     *
     * @return the value of player.league
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public String getLeague() {
        return league;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.league
     *
     * @param league the value for player.league
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public void setLeague(String league) {
        this.league = league == null ? null : league.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.tier
     *
     * @return the value of player.tier
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public Integer getTier() {
        return tier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.tier
     *
     * @param tier the value for player.tier
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public void setTier(Integer tier) {
        this.tier = tier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.mmr
     *
     * @return the value of player.mmr
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public Integer getMmr() {
        return mmr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.mmr
     *
     * @param mmr the value for player.mmr
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public void setMmr(Integer mmr) {
        this.mmr = mmr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.points
     *
     * @return the value of player.points
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public Integer getPoints() {
        return points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.points
     *
     * @param points the value for player.points
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public void setPoints(Integer points) {
        this.points = points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.wins
     *
     * @return the value of player.wins
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public Integer getWins() {
        return wins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.wins
     *
     * @param wins the value for player.wins
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public void setWins(Integer wins) {
        this.wins = wins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.losses
     *
     * @return the value of player.losses
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public Integer getLosses() {
        return losses;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.losses
     *
     * @param losses the value for player.losses
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public void setLosses(Integer losses) {
        this.losses = losses;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.ties
     *
     * @return the value of player.ties
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public Integer getTies() {
        return ties;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.ties
     *
     * @param ties the value for player.ties
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public void setTies(Integer ties) {
        this.ties = ties;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.ladderid
     *
     * @return the value of player.ladderid
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public Integer getLadderid() {
        return ladderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.ladderid
     *
     * @param ladderid the value for player.ladderid
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public void setLadderid(Integer ladderid) {
        this.ladderid = ladderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.updateTime
     *
     * @return the value of player.updateTime
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public Integer getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.updateTime
     *
     * @param updatetime the value for player.updateTime
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public void setUpdatetime(Integer updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.lastPlayedTime
     *
     * @return the value of player.lastPlayedTime
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public Integer getLastplayedtime() {
        return lastplayedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.lastPlayedTime
     *
     * @param lastplayedtime the value for player.lastPlayedTime
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public void setLastplayedtime(Integer lastplayedtime) {
        this.lastplayedtime = lastplayedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.joinTime
     *
     * @return the value of player.joinTime
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public Integer getJointime() {
        return jointime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.joinTime
     *
     * @param jointime the value for player.joinTime
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public void setJointime(Integer jointime) {
        this.jointime = jointime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.winRate
     *
     * @return the value of player.winRate
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public Integer getWinrate() {
        return winrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.winRate
     *
     * @param winrate the value for player.winRate
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public void setWinrate(Integer winrate) {
        this.winrate = winrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.profilePath
     *
     * @return the value of player.profilePath
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public String getProfilepath() {
        return profilepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.profilePath
     *
     * @param profilepath the value for player.profilePath
     *
     * @mbg.generated Thu Dec 01 12:30:10 CST 2016
     */
    public void setProfilepath(String profilepath) {
        this.profilepath = profilepath == null ? null : profilepath.trim();
    }
}