package com.scarb.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_ID
     *
     * @mbg.generated Tue Sep 27 04:43:34 CST 2016
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_NAME
     *
     * @mbg.generated Tue Sep 27 04:43:34 CST 2016
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_PASSWORD
     *
     * @mbg.generated Tue Sep 27 04:43:34 CST 2016
     */
    private String userPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_EMAIL
     *
     * @mbg.generated Tue Sep 27 04:43:34 CST 2016
     */
    private String userEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_GAMEID
     *
     * @mbg.generated Tue Sep 27 04:43:34 CST 2016
     */
    private Integer userGameid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_GAMENAME
     *
     * @mbg.generated Tue Sep 27 04:43:34 CST 2016
     */
    private String userGamename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_ID
     *
     * @return the value of user.USER_ID
     *
     * @mbg.generated Tue Sep 27 04:43:34 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_ID
     *
     * @param userId the value for user.USER_ID
     *
     * @mbg.generated Tue Sep 27 04:43:34 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_NAME
     *
     * @return the value of user.USER_NAME
     *
     * @mbg.generated Tue Sep 27 04:43:34 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_NAME
     *
     * @param userName the value for user.USER_NAME
     *
     * @mbg.generated Tue Sep 27 04:43:34 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_PASSWORD
     *
     * @return the value of user.USER_PASSWORD
     *
     * @mbg.generated Tue Sep 27 04:43:34 CST 2016
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_PASSWORD
     *
     * @param userPassword the value for user.USER_PASSWORD
     *
     * @mbg.generated Tue Sep 27 04:43:34 CST 2016
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_EMAIL
     *
     * @return the value of user.USER_EMAIL
     *
     * @mbg.generated Tue Sep 27 04:43:34 CST 2016
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_EMAIL
     *
     * @param userEmail the value for user.USER_EMAIL
     *
     * @mbg.generated Tue Sep 27 04:43:34 CST 2016
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_GAMEID
     *
     * @return the value of user.USER_GAMEID
     *
     * @mbg.generated Tue Sep 27 04:43:34 CST 2016
     */
    public Integer getUserGameid() {
        return userGameid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_GAMEID
     *
     * @param userGameid the value for user.USER_GAMEID
     *
     * @mbg.generated Tue Sep 27 04:43:34 CST 2016
     */
    public void setUserGameid(Integer userGameid) {
        this.userGameid = userGameid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_GAMENAME
     *
     * @return the value of user.USER_GAMENAME
     *
     * @mbg.generated Tue Sep 27 04:43:34 CST 2016
     */
    public String getUserGamename() {
        return userGamename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_GAMENAME
     *
     * @param userGamename the value for user.USER_GAMENAME
     *
     * @mbg.generated Tue Sep 27 04:43:34 CST 2016
     */
    public void setUserGamename(String userGamename) {
        this.userGamename = userGamename == null ? null : userGamename.trim();
    }
}