package com.scarb.mapper;

import com.scarb.model.Ladder;
import com.scarb.model.LadderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LadderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ladder
     *
     * @mbggenerated Thu Sep 08 15:30:41 CST 2016
     */
    int countByExample(LadderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ladder
     *
     * @mbggenerated Thu Sep 08 15:30:41 CST 2016
     */
    int deleteByExample(LadderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ladder
     *
     * @mbggenerated Thu Sep 08 15:30:41 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ladder
     *
     * @mbggenerated Thu Sep 08 15:30:41 CST 2016
     */
    int insert(Ladder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ladder
     *
     * @mbggenerated Thu Sep 08 15:30:41 CST 2016
     */
    int insertSelective(Ladder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ladder
     *
     * @mbggenerated Thu Sep 08 15:30:41 CST 2016
     */
    List<Ladder> selectByExample(LadderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ladder
     *
     * @mbggenerated Thu Sep 08 15:30:41 CST 2016
     */
    Ladder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ladder
     *
     * @mbggenerated Thu Sep 08 15:30:41 CST 2016
     */
    int updateByExampleSelective(@Param("record") Ladder record, @Param("example") LadderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ladder
     *
     * @mbggenerated Thu Sep 08 15:30:41 CST 2016
     */
    int updateByExample(@Param("record") Ladder record, @Param("example") LadderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ladder
     *
     * @mbggenerated Thu Sep 08 15:30:41 CST 2016
     */
    int updateByPrimaryKeySelective(Ladder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ladder
     *
     * @mbggenerated Thu Sep 08 15:30:41 CST 2016
     */
    int updateByPrimaryKey(Ladder record);
}